env:
  global:
    - "SFTP_USER=[user]"
    - "SFTP_PASSWORD=[password]"
    - "SFTP_KEY=[base64-encoded-rsa-key]"
  after_success:
    #- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
    #- curl --ftp-create-dirs
    #  -T filename
    #  --key /tmp/sftp_rsa
    #  sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename

    find ./uploads/ -type f -exec curl -u web232:W5xnTmH6EyadMwFG --ftp-create-dirs -T {} ftp://s96.goserver.host/petetest/wp-content/uploads/{} \;
